CREATE TABLE user_m(
	user_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(100) NOT NULL,
	nama_depan VARCHAR(100) NOT NULL,
	nama_belakang VARCHAR(100) NOT NULL,
	photo text NULL,
	password VARCHAR(255) NOT NULL,
	token TEXT NULL
)ENGINE=INNODB;

CREATE TABLE userbalance_m (
	userbalance_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER UNIQUE,
	balance BIGINT,
	created_at DATETIME,
	updated_at DATETIME
)ENGINE=INNODB